name: Unit Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Build core
        run: yarn build:core
      - name: Run tests of ${{ matrix.node }}
        run: yarn test
